### ISSUE TITLE
CA-Certificate Error during build

### ISSUE THREAD

**Issue by viable-hartman** [Andolamin/meta-rpi-luneos#12]
ERROR: Task 2196 (/build/webos-ports-env/webos-ports/openembedded-core/meta/recipes-support/ca-certificates/ca-certificates_20141019.bb, do_install) failed with exit code '1'

I'm assuming its not downloading the certs.

**Comment by Andolamin** [comment]
I haven't seen this issue, but it's occurring in the openembedded-core recipes, so not affected by this layer.
