### ISSUE TITLE
Screen dpi is not accounted for

### ISSUE THREAD

**Issue by Andolamin** [Andolamin/meta-rpi-luneos#4]
Apps (like the Just type... search) scale oddly on the screen. Particularly, the Just type... search box in the app looks vertically squashed.

**Comment by Herrie82** [comment]
We use Grid Units for our devices to have a similar experience across devices. You need to make sure to have the right value setup in your lunasysmgr -conf for your target. As per https://github.com/webOS-ports/luna-sysmgr/blob/webOS-ports/master/conf/luna-tenderloin.conf#L35

For Mako GridUnit = 18.
